name: Generate Fireball Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Criar pasta dist
        run: mkdir -p dist

      - name: Gerar fireball.svg
        run: |
          cat > dist/fireball.svg << 'EOF'
          <svg width="300" height="60" xmlns="http://www.w3.org/2000/svg" >
            <rect x="10" y="20" width="20" height="20" fill="#0c422d" />
            <rect x="40" y="20" width="20" height="20" fill="#14532d" />
            <rect x="70" y="20" width="20" height="20" fill="#166534" />
            <rect x="100" y="20" width="20" height="20" fill="#4ade80" />
            <rect x="130" y="20" width="20" height="20" fill="#a7f3d0" />

            <circle cx="0" cy="30" r="15" fill="orange" filter="url(#fireGlow)">
              <animate attributeName="cx" from="0" to="150" dur="4s" repeatCount="indefinite" />
            </circle>

            <rect x="10" y="20" width="20" height="20" fill="#0c422d">
              <animate attributeName="fill-opacity" values="1;0;1" dur="4s" begin="0s" repeatCount="indefinite"/>
            </rect>
            <rect x="40" y="20" width="20" height="20" fill="#14532d">
              <animate attributeName="fill-opacity" values="1;0;1" dur="4s" begin="0.8s" repeatCount="indefinite"/>
            </rect>
            <rect x="70" y="20" width="20" height="20" fill="#166534">
              <animate attributeName="fill-opacity" values="1;0;1" dur="4s" begin="1.6s" repeatCount="indefinite"/>
            </rect>
            <rect x="100" y="20" width="20" height="20" fill="#4ade80">
              <animate attributeName="fill-opacity" values="1;0;1" dur="4s" begin="2.4s" repeatCount="indefinite"/>
            </rect>
            <rect x="130" y="20" width="20" height="20" fill="#a7f3d0">
              <animate attributeName="fill-opacity" values="1;0;1" dur="4s" begin="3.2s" repeatCount="indefinite"/>
            </rect>

            <defs>
              <filter id="fireGlow" x="-50%" y="-50%" width="200%" height="200%">
                <feDropShadow dx="0" dy="0" stdDeviation="4" flood-color="orange" flood-opacity="0.9"/>
                <feDropShadow dx="0" dy="0" stdDeviation="10" flood-color="yellow" flood-opacity="0.6"/>
              </filter>
            </defs>
          </svg>
          EOF

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
